# Generated by Django 5.1.5 on 2025-07-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar_app', '0002_webinarbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinarbooking',
            name='razorpay_order_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
